### PR TITLE
Modify CMakeList.txt

### PR DESCRIPTION
**Pull request by barnjamin**
This looks like great work! Can't wait to try it.  Had to make a slight modification to get this to compile, still working to validate the change though.

With `Core` in target_link_libraries, cmake complained about linking to an OBJECT_LIBRARY. Tried adding $<TARGET_OBJECTS:Core> to cuda_add_library, cmake didn't like it. Just removing cuda prefix from add_libraries command let this compile.  I'd be happy to get this declined with a better alternative.

### CODE REVIEW

**Comment by theNded** [comment]
Hi, thank you for your interest!
I modified my cuda_add_library and it works with my cmake (bundled in CLion, version 3.12.2). Not sure why it fails in your case. I prefer to keep the prefix because otherwise the project may fail to evoke nvcc to compile the files.

This cuda branch is in early stage under development, and I cannot guarantee the stability or compatibility at all -- I do apologize for it. Since I work on my own, I expect to complete the basic functions in one or two months. Before that, I can only ensure it to be compilable on my machine.
(emmmm I may update this paragraph in my README.md)

**Comment by barnjamin** [comment]
Understood.  I'll close this pr, if there is any way you can share the cuda_add_library modification I'd appreciate it.  Otherwise I'll just keep stalking the changes here.
Thanks!

**Comment by barnjamin** [comment]
Just to follow up with this, installing a later version of CMake (3.5=>3.12.3) for the include issues and Eigen (3.2.9=>3.3.9) for some compilation issues allows this to compile for me on a TX2. Adding
 ```
-gencode=arch=compute_62,code=sm_62
``` 
makes the tests pass. Looks great so far!

**Comment by tanajikamble13** [comment]
@barnjamin please let me know where I should update the changes suggested by you

**Comment by barnjamin** [comment]
i dont remember the file name, but grep for gencode itll and probably tell you

**Pull request closed without merging**
